[proxy]
bind = "0.0.0.0"
port = 8181

[policy]
url = 'http://localhost:8080/'
policy = '/example/basic/allow'
default = "allow"

[repositories.crates-io]
type = "crates"
#url = "https://crates.io/"
url = "https://github.com/rust-lang/crates.io-index"

[repositories.m2]
type = "m2"
url = "https://repo.maven.apache.org/maven2"
